### ISSUE TITLE
grunt server says address is already in use

### ISSUE THREAD

**Issue by sigmike** [gruntjs/grunt-cli#109]
When I run `grunt server` it seems to start the application twice and fails because the port is already in use:

```
$ grunt server
[...]
✖ 7 problems (0 errors, 7 warnings)


Running "develop:server" (develop) task

[grunt-develop] > started application "app.js".
[grunt-develop] > started application "app.js".
[grunt-develop] > Open Source Universal Remote UI + API has started on port 3000 (http).

[grunt-develop] > Open Source Universal Remote UI + API has started on port 3000 (http).

[grunt-develop] > events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at Server.listen (net.js:1385:5)
    at EventEmitter.listen (/home/mike/devel/lirc_web/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/home/mike/devel/lirc_web/app.js:212:7)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
>> application exited with code 1

Running "watch" task
Waiting...

Done, without errors.

```

I just installed `grunt-cli` (1.2.0) and `grunt-init` (0.3.2).

**Comment by shama** [comment]
This project, `grunt-cli`, is only responsible for providing a command line interface to run Grunt. The `server` task is provided likely by 3rd party plugin/s. I recommend trying stackoverflow or the issue tracker for the plugin that is starting the server instead as I'm not familiar with them.

**Comment by sigmike** [comment]
Oh I posted this on the wrong repository. Sorry.
