### ISSUE TITLE
After upgrading node/npm on OSX I'm getting `Cannot read property 'find' of undefined` when installing grunt-cli

### ISSUE THREAD

**Issue by thehashrocket** [gruntjs/grunt-cli#114]
This is the log file from the install that showing the error. It's happening around line 252:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'grunt-cli' ]
2 info using npm@5.0.1
3 info using node@v8.0.0
4 silly install loadCurrentTree
5 silly install readGlobalPackageData
6 http fetch GET 304 https://registry.npmjs.org/grunt-cli 422ms (from cache)
7 silly pacote tag manifest for grunt-cli@latest fetched in 461ms
8 silly install loadIdealTree
9 silly install cloneCurrentTreeToIdealTree
10 silly install loadShrinkwrap
11 silly install loadAllDepsIntoIdealTree
12 silly resolveWithNewModule grunt-cli@1.2.0 checking installable status
13 http fetch GET 304 https://registry.npmjs.org/grunt-known-options 278ms (from cache)
14 silly pacote range manifest for grunt-known-options@~1.1.0 fetched in 281ms
15 silly resolveWithNewModule grunt-known-options@1.1.0 checking installable status
16 http fetch GET 304 https://registry.npmjs.org/findup-sync 317ms (from cache)
17 silly pacote range manifest for findup-sync@~0.3.0 fetched in 320ms
18 silly resolveWithNewModule findup-sync@0.3.0 checking installable status
19 http fetch GET 304 https://registry.npmjs.org/nopt 319ms (from cache)
20 silly pacote range manifest for nopt@~3.0.6 fetched in 322ms
21 silly resolveWithNewModule nopt@3.0.6 checking installable status
22 http fetch GET 304 https://registry.npmjs.org/resolve 544ms (from cache)
23 silly pacote range manifest for resolve@~1.1.0 fetched in 551ms
24 silly resolveWithNewModule resolve@1.1.7 checking installable status
25 http fetch GET 304 https://registry.npmjs.org/glob 277ms (from cache)
26 silly pacote range manifest for glob@~5.0.0 fetched in 292ms
27 silly resolveWithNewModule glob@5.0.15 checking installable status
28 http fetch GET 304 https://registry.npmjs.org/inflight 94ms (from cache)
29 http fetch GET 304 https://registry.npmjs.org/inherits 95ms (from cache)
30 silly pacote range manifest for inflight@^1.0.4 fetched in 95ms
31 silly resolveWithNewModule inflight@1.0.6 checking installable status
32 silly pacote range manifest for inherits@2 fetched in 96ms
33 silly resolveWithNewModule inherits@2.0.3 checking installable status
34 http fetch GET 304 https://registry.npmjs.org/once 304ms (from cache)
35 http fetch GET 304 https://registry.npmjs.org/minimatch 305ms (from cache)
36 silly pacote range manifest for once@^1.3.0 fetched in 307ms
37 silly resolveWithNewModule once@1.4.0 checking installable status
38 silly pacote range manifest for minimatch@2 || 3 fetched in 308ms
39 silly resolveWithNewModule minimatch@3.0.4 checking installable status
40 http fetch GET 304 https://registry.npmjs.org/path-is-absolute 358ms (from cache)
41 silly pacote range manifest for path-is-absolute@^1.0.0 fetched in 360ms
42 silly resolveWithNewModule path-is-absolute@1.0.1 checking installable status
43 http fetch GET 304 https://registry.npmjs.org/wrappy 78ms (from cache)
44 silly pacote range manifest for wrappy@1 fetched in 79ms
45 silly resolveWithNewModule wrappy@1.0.2 checking installable status
46 http fetch GET 304 https://registry.npmjs.org/brace-expansion 279ms (from cache)
47 silly pacote range manifest for brace-expansion@^1.1.7 fetched in 280ms
48 silly resolveWithNewModule brace-expansion@1.1.7 checking installable status
49 http fetch GET 304 https://registry.npmjs.org/balanced-match 79ms (from cache)
50 silly pacote range manifest for balanced-match@^0.4.1 fetched in 80ms
51 silly resolveWithNewModule balanced-match@0.4.2 checking installable status
52 http fetch GET 304 https://registry.npmjs.org/concat-map 277ms (from cache)
53 silly pacote version manifest for concat-map@0.0.1 fetched in 278ms
54 silly resolveWithNewModule concat-map@0.0.1 checking installable status
55 http fetch GET 304 https://registry.npmjs.org/abbrev 76ms (from cache)
56 silly pacote range manifest for abbrev@1 fetched in 77ms
57 silly resolveWithNewModule abbrev@1.1.0 checking installable status
58 silly currentTree lib
59 silly idealTree lib
59 silly idealTree └─┬ grunt-cli@1.2.0
59 silly idealTree   ├── abbrev@1.1.0
59 silly idealTree   ├── balanced-match@0.4.2
59 silly idealTree   ├── brace-expansion@1.1.7
59 silly idealTree   ├── concat-map@0.0.1
59 silly idealTree   ├── findup-sync@0.3.0
59 silly idealTree   ├── glob@5.0.15
59 silly idealTree   ├── grunt-known-options@1.1.0
59 silly idealTree   ├── inflight@1.0.6
59 silly idealTree   ├── inherits@2.0.3
59 silly idealTree   ├── minimatch@3.0.4
59 silly idealTree   ├── nopt@3.0.6
59 silly idealTree   ├── once@1.4.0
59 silly idealTree   ├── path-is-absolute@1.0.1
59 silly idealTree   ├── resolve@1.1.7
59 silly idealTree   └── wrappy@1.0.2
60 silly install generateActionsToTake
61 silly diffTrees action count 16
62 silly diffTrees add abbrev@1.1.0
63 silly diffTrees add balanced-match@0.4.2
64 silly diffTrees add concat-map@0.0.1
65 silly diffTrees add brace-expansion@1.1.7
66 silly diffTrees add inherits@2.0.3
67 silly diffTrees add minimatch@3.0.4
68 silly diffTrees add path-is-absolute@1.0.1
69 silly diffTrees add wrappy@1.0.2
70 silly diffTrees add once@1.4.0
71 silly diffTrees add inflight@1.0.6
72 silly diffTrees add glob@5.0.15
73 silly diffTrees add findup-sync@0.3.0
74 silly diffTrees add grunt-known-options@1.1.0
75 silly diffTrees add nopt@3.0.6
76 silly diffTrees add resolve@1.1.7
77 silly diffTrees add grunt-cli@1.2.0
78 silly decomposeActions action count 128
79 silly decomposeActions fetch abbrev@1.1.0
80 silly decomposeActions extract abbrev@1.1.0
81 silly decomposeActions preinstall abbrev@1.1.0
82 silly decomposeActions build abbrev@1.1.0
83 silly decomposeActions install abbrev@1.1.0
84 silly decomposeActions postinstall abbrev@1.1.0
85 silly decomposeActions finalize abbrev@1.1.0
86 silly decomposeActions refresh-package-json abbrev@1.1.0
87 silly decomposeActions fetch balanced-match@0.4.2
88 silly decomposeActions extract balanced-match@0.4.2
89 silly decomposeActions preinstall balanced-match@0.4.2
90 silly decomposeActions build balanced-match@0.4.2
91 silly decomposeActions install balanced-match@0.4.2
92 silly decomposeActions postinstall balanced-match@0.4.2
93 silly decomposeActions finalize balanced-match@0.4.2
94 silly decomposeActions refresh-package-json balanced-match@0.4.2
95 silly decomposeActions fetch concat-map@0.0.1
96 silly decomposeActions extract concat-map@0.0.1
97 silly decomposeActions preinstall concat-map@0.0.1
98 silly decomposeActions build concat-map@0.0.1
99 silly decomposeActions install concat-map@0.0.1
100 silly decomposeActions postinstall concat-map@0.0.1
101 silly decomposeActions finalize concat-map@0.0.1
102 silly decomposeActions refresh-package-json concat-map@0.0.1
103 silly decomposeActions fetch brace-expansion@1.1.7
104 silly decomposeActions extract brace-expansion@1.1.7
105 silly decomposeActions preinstall brace-expansion@1.1.7
106 silly decomposeActions build brace-expansion@1.1.7
107 silly decomposeActions install brace-expansion@1.1.7
108 silly decomposeActions postinstall brace-expansion@1.1.7
109 silly decomposeActions finalize brace-expansion@1.1.7
110 silly decomposeActions refresh-package-json brace-expansion@1.1.7
111 silly decomposeActions fetch inherits@2.0.3
112 silly decomposeActions extract inherits@2.0.3
113 silly decomposeActions preinstall inherits@2.0.3
114 silly decomposeActions build inherits@2.0.3
115 silly decomposeActions install inherits@2.0.3
116 silly decomposeActions postinstall inherits@2.0.3
117 silly decomposeActions finalize inherits@2.0.3
118 silly decomposeActions refresh-package-json inherits@2.0.3
119 silly decomposeActions fetch minimatch@3.0.4
120 silly decomposeActions extract minimatch@3.0.4
121 silly decomposeActions preinstall minimatch@3.0.4
122 silly decomposeActions build minimatch@3.0.4
123 silly decomposeActions install minimatch@3.0.4
124 silly decomposeActions postinstall minimatch@3.0.4
125 silly decomposeActions finalize minimatch@3.0.4
126 silly decomposeActions refresh-package-json minimatch@3.0.4
127 silly decomposeActions fetch path-is-absolute@1.0.1
128 silly decomposeActions extract path-is-absolute@1.0.1
129 silly decomposeActions preinstall path-is-absolute@1.0.1
130 silly decomposeActions build path-is-absolute@1.0.1
131 silly decomposeActions install path-is-absolute@1.0.1
132 silly decomposeActions postinstall path-is-absolute@1.0.1
133 silly decomposeActions finalize path-is-absolute@1.0.1
134 silly decomposeActions refresh-package-json path-is-absolute@1.0.1
135 silly decomposeActions fetch wrappy@1.0.2
136 silly decomposeActions extract wrappy@1.0.2
137 silly decomposeActions preinstall wrappy@1.0.2
138 silly decomposeActions build wrappy@1.0.2
139 silly decomposeActions install wrappy@1.0.2
140 silly decomposeActions postinstall wrappy@1.0.2
141 silly decomposeActions finalize wrappy@1.0.2
142 silly decomposeActions refresh-package-json wrappy@1.0.2
143 silly decomposeActions fetch once@1.4.0
144 silly decomposeActions extract once@1.4.0
145 silly decomposeActions preinstall once@1.4.0
146 silly decomposeActions build once@1.4.0
147 silly decomposeActions install once@1.4.0
148 silly decomposeActions postinstall once@1.4.0
149 silly decomposeActions finalize once@1.4.0
150 silly decomposeActions refresh-package-json once@1.4.0
151 silly decomposeActions fetch inflight@1.0.6
152 silly decomposeActions extract inflight@1.0.6
153 silly decomposeActions preinstall inflight@1.0.6
154 silly decomposeActions build inflight@1.0.6
155 silly decomposeActions install inflight@1.0.6
156 silly decomposeActions postinstall inflight@1.0.6
157 silly decomposeActions finalize inflight@1.0.6
158 silly decomposeActions refresh-package-json inflight@1.0.6
159 silly decomposeActions fetch glob@5.0.15
160 silly decomposeActions extract glob@5.0.15
161 silly decomposeActions preinstall glob@5.0.15
162 silly decomposeActions build glob@5.0.15
163 silly decomposeActions install glob@5.0.15
164 silly decomposeActions postinstall glob@5.0.15
165 silly decomposeActions finalize glob@5.0.15
166 silly decomposeActions refresh-package-json glob@5.0.15
167 silly decomposeActions fetch findup-sync@0.3.0
168 silly decomposeActions extract findup-sync@0.3.0
169 silly decomposeActions preinstall findup-sync@0.3.0
170 silly decomposeActions build findup-sync@0.3.0
171 silly decomposeActions install findup-sync@0.3.0
172 silly decomposeActions postinstall findup-sync@0.3.0
173 silly decomposeActions finalize findup-sync@0.3.0
174 silly decomposeActions refresh-package-json findup-sync@0.3.0
175 silly decomposeActions fetch grunt-known-options@1.1.0
176 silly decomposeActions extract grunt-known-options@1.1.0
177 silly decomposeActions preinstall grunt-known-options@1.1.0
178 silly decomposeActions build grunt-known-options@1.1.0
179 silly decomposeActions install grunt-known-options@1.1.0
180 silly decomposeActions postinstall grunt-known-options@1.1.0
181 silly decomposeActions finalize grunt-known-options@1.1.0
182 silly decomposeActions refresh-package-json grunt-known-options@1.1.0
183 silly decomposeActions fetch nopt@3.0.6
184 silly decomposeActions extract nopt@3.0.6
185 silly decomposeActions preinstall nopt@3.0.6
186 silly decomposeActions build nopt@3.0.6
187 silly decomposeActions install nopt@3.0.6
188 silly decomposeActions postinstall nopt@3.0.6
189 silly decomposeActions finalize nopt@3.0.6
190 silly decomposeActions refresh-package-json nopt@3.0.6
191 silly decomposeActions fetch resolve@1.1.7
192 silly decomposeActions extract resolve@1.1.7
193 silly decomposeActions preinstall resolve@1.1.7
194 silly decomposeActions build resolve@1.1.7
195 silly decomposeActions install resolve@1.1.7
196 silly decomposeActions postinstall resolve@1.1.7
197 silly decomposeActions finalize resolve@1.1.7
198 silly decomposeActions refresh-package-json resolve@1.1.7
199 silly decomposeActions fetch grunt-cli@1.2.0
200 silly decomposeActions extract grunt-cli@1.2.0
201 silly decomposeActions preinstall grunt-cli@1.2.0
202 silly decomposeActions build grunt-cli@1.2.0
203 silly decomposeActions install grunt-cli@1.2.0
204 silly decomposeActions postinstall grunt-cli@1.2.0
205 silly decomposeActions finalize grunt-cli@1.2.0
206 silly decomposeActions refresh-package-json grunt-cli@1.2.0
207 silly install executeActions
208 silly doSerial global-install 128
209 verbose correctMkdir /Users/jasonshultz/.npm/_locks correctMkdir not in flight; initializing
210 verbose lock using /Users/jasonshultz/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
211 silly doParallel extract 128
212 silly extract abbrev@1.1.0
213 silly pacote trying abbrev@https://registry.npmjs.org/abbrev/-/abbrev-1.1.0.tgz by hash: sha1-0FVMIlZjbi9W58LlrRg/hZQo2B8=
214 silly extract balanced-match@0.4.2
215 silly pacote trying balanced-match@https://registry.npmjs.org/balanced-match/-/balanced-match-0.4.2.tgz by hash: sha1-yz8+PHMtwPAe5wtAPzAuYddwmDg=
216 silly extract concat-map@0.0.1
217 silly pacote trying concat-map@https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz by hash: sha1-2Klr13/Wjfd5OnMDajug1UBdR3s=
218 silly extract brace-expansion@1.1.7
219 silly pacote trying brace-expansion@https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.7.tgz by hash: sha1-Pv/DxQ4ABTH7cg6v+A8K6O8jz1k=
220 silly extract inherits@2.0.3
221 silly pacote trying inherits@https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz by hash: sha1-Yzwsg+PaQqUC9SRmAiSA9CCCYd4=
222 silly extract minimatch@3.0.4
223 silly pacote trying minimatch@https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz by hash: sha512-yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==
224 silly extract path-is-absolute@1.0.1
225 silly pacote trying path-is-absolute@https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz by hash: sha1-F0uSaHNVNP+8es5r9TpanhtcX18=
226 silly extract wrappy@1.0.2
227 silly pacote trying wrappy@https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz by hash: sha1-tSQ9jz7BqjXxNkYFvA0QNuMKtp8=
228 silly extract once@1.4.0
229 silly pacote trying once@https://registry.npmjs.org/once/-/once-1.4.0.tgz by hash: sha1-WDsap3WWHUsROsF9nFC6753Xa9E=
230 silly extract inflight@1.0.6
231 silly pacote trying inflight@https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz by hash: sha1-Sb1jMdfQLQwJvJEKEHW6gWW1bfk=
232 silly extract glob@5.0.15
233 silly pacote trying glob@https://registry.npmjs.org/glob/-/glob-5.0.15.tgz by hash: sha1-G8k2ueAvSmA/zCIuz3Yz0wuLk7E=
234 silly extract findup-sync@0.3.0
235 silly pacote trying findup-sync@https://registry.npmjs.org/findup-sync/-/findup-sync-0.3.0.tgz by hash: sha1-N5MKpdgWt3fANEXhlmzGeQpMCxY=
236 silly extract grunt-known-options@1.1.0
237 silly pacote trying grunt-known-options@https://registry.npmjs.org/grunt-known-options/-/grunt-known-options-1.1.0.tgz by hash: sha1-pCdO6zL6dl2lp6OxcSYXzjsUQUk=
238 silly extract nopt@3.0.6
239 silly pacote trying nopt@https://registry.npmjs.org/nopt/-/nopt-3.0.6.tgz by hash: sha1-xkZdvwirzU2zWTF/eaxopkayj/k=
240 silly extract resolve@1.1.7
241 silly pacote trying resolve@https://registry.npmjs.org/resolve/-/resolve-1.1.7.tgz by hash: sha1-IDEU2CrSxe2ejgQRs5ModeiJ6Xs=
242 silly extract grunt-cli@1.2.0
243 silly pacote trying grunt-cli@https://registry.npmjs.org/grunt-cli/-/grunt-cli-1.2.0.tgz by hash: sha1-VisRnrsGndtGSs4oRVAb6Xs1tqg=
244 silly pacote data for sha512-yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA== not present. Using manifest.
245 silly pacote brace-expansion@https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.7.tgz extracted to /usr/local/lib/node_modules/.staging/brace-expansion-2db85e18 by content address 50ms
246 silly pacote abbrev@https://registry.npmjs.org/abbrev/-/abbrev-1.1.0.tgz extracted to /usr/local/lib/node_modules/.staging/abbrev-693b29c1 by content address 64ms
247 silly pacote path-is-absolute@https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz extracted to /usr/local/lib/node_modules/.staging/path-is-absolute-0ac07215 by content address 58ms
248 silly pacote once@https://registry.npmjs.org/once/-/once-1.4.0.tgz extracted to /usr/local/lib/node_modules/.staging/once-c5e08187 by content address 57ms
249 silly pacote grunt-known-options@https://registry.npmjs.org/grunt-known-options/-/grunt-known-options-1.1.0.tgz extracted to /usr/local/lib/node_modules/.staging/grunt-known-options-36984651 by content address 55ms
250 silly pacote inflight@https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz extracted to /usr/local/lib/node_modules/.staging/inflight-50f98cd4 by content address 58ms
251 silly pacote wrappy@https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz extracted to /usr/local/lib/node_modules/.staging/wrappy-2e68a4eb by content address 59ms
252 verbose stack TypeError: Cannot read property 'find' of undefined
252 verbose stack     at opts.integrity.digests.find.hash (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:264:33)
252 verbose stack     at Array.find (native)
252 verbose stack     at Transform.on (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:263:15)
252 verbose stack     at emitNone (events.js:110:20)
252 verbose stack     at Transform.emit (events.js:207:7)
252 verbose stack     at endReadableNT (_stream_readable.js:1045:12)
252 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:102:11)
252 verbose stack     at process._tickCallback (internal/process/next_tick.js:161:9)
253 verbose cwd /Users/jasonshultz/Projects/3form
254 verbose Darwin 16.6.0
255 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "grunt-cli"
256 verbose node v8.0.0
257 verbose npm  v5.0.1
258 error Cannot read property 'find' of undefined
259 verbose exit [ 1, true ]
```

**Comment by thehashrocket** [comment]
I'm using Node 8.0.0 and NPM 5.0.1

**Comment by shama** [comment]
This looks like an error from `npm`, specifically the module `ssri`:

```
verbose stack     at opts.integrity.digests.find.hash (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:264:33)
252 verbose 
```

Specifically [this line](https://github.com/zkat/ssri/blob/latest/index.js#L264).

Would you mind opening this issue on [ssri](https://github.com/zkat/ssri/issues) or [npm](https://github.com/npm/npm/issues)?

**Comment by thehashrocket** [comment]
Ok, done. :) Thank you!
