### ISSUE TITLE
grunt --tasks broken

### ISSUE THREAD

**Issue by LandonSchropp** [gruntjs/grunt-cli#29]
I'm using grunt version 0.4.1 and grunt-cli version 0.1.9. If I add this Gruntfile:

``` javascript
module.exports = function(grunt) {};
```

And I run `grunt --tasks`, I get the following error:

```
path.js:360
        throw new TypeError('Arguments to path.join must be strings');
              ^
TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at Object.file.exists (/Users/landonschropp/Development/example/node_modules/grunt/lib/grunt/file.js:371:28)
    at task.loadTasks (/Users/landonschropp/Development/example/node_modules/grunt/lib/grunt/task.js:358:18)
    at Array.forEach (native)
    at Task.task.init (/Users/landonschropp/Development/example/node_modules/grunt/lib/grunt/task.js:444:33)
    at Object.grunt.tasks (/Users/landonschropp/Development/example/node_modules/grunt/lib/grunt.js:113:8)
    at Object.module.exports [as cli] (/Users/landonschropp/Development/example/node_modules/grunt/lib/grunt/cli.js:38:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/grunt-cli/bin/grunt:41:20)
```

**Comment by bisrael** [comment]
@ulidtko -- do `grunt -h` and you'll see the available tasks after all of the options you can pass.

**Comment by shamess** [comment]
Thanks, @bisrael. That was what I was looking for too - didn't spot it first time around.
