### ISSUE TITLE
Not sure if this is a grunt issue or npm

### ISSUE THREAD

**Issue by SimpleMajority** [gruntjs/grunt-cli#51]
I am posting this issue here as npm seems to be functioning fine, but when I attempt to install grunt-cli I get this error log. I tried adding sudo and also logging in as su with no luck.

```
info it worked if it ends with ok
verbose cli [ 'node', '/usr/bin/npm', 'install', '-g', 'grunt-cli' ]
info using npm@1.1.4
info using node@v0.6.12
verbose config file /home/local/.npmrc
verbose config file /usr/etc/npmrc
verbose config file /usr/share/npm/npmrc
silly exec /usr/bin/node "/usr/share/npm/bin/npm-get-uid-gid.js" "nobody" 1000
silly spawning [ '/usr/bin/node',
silly spawning   [ '/usr/share/npm/bin/npm-get-uid-gid.js', 'nobody', 1000 ],
silly spawning   null ]
silly output from getuid/gid {"uid":65534,"gid":1000}
silly output from getuid/gid 
verbose cache add [ 'grunt-cli', null ]
silly cache add: name, spec, args [ undefined, 'grunt-cli', [ 'grunt-cli', null ] ]
verbose parsed url { pathname: 'grunt-cli', path: 'grunt-cli', href: 'grunt-cli' }
verbose addNamed [ 'grunt-cli', '' ]
verbose addNamed [ null, '' ]
silly name, range, hasData [ 'grunt-cli', '', false ]
verbose raw, before any munging grunt-cli
verbose url resolving [ 'https://registry.npmjs.org/', './grunt-cli' ]
verbose url resolved https://registry.npmjs.org/grunt-cli
http GET https://registry.npmjs.org/grunt-cli
ERR! Error: failed to fetch from registry: grunt-cli
ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
ERR!     at Request.emit (events.js:88:20)
ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
ERR!     at ClientRequest.emit (events.js:67:17)
ERR!     at HTTPParser.onIncoming (http.js:1261:11)
ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
ERR! You may report this log at:
ERR!     <http://bugs.debian.org/npm>
ERR! or use
ERR!     reportbug --attach /var/www/html/symfony/npm-debug.log npm
ERR! 
ERR! System Linux 3.8.0-29-generic
ERR! command "node" "/usr/bin/npm" "install" "-g" "grunt-cli"
ERR! cwd /var/www/html/symfony
ERR! node -v v0.6.12
ERR! npm -v 1.1.4
ERR! message failed to fetch from registry: grunt-cli
verbose exit [ 1, true ]
```

**Comment by vinnyfs89** [comment]
You tried this command below? 
npm config set registry http://registry.npmjs.org/
